apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-demo
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: demo-page
    literals:
      - index.html=Stage A Flux demo - revision 2
