---
- name: Restart Forgejo Runner instances
  ansible.builtin.systemd_service:
    name: "{{ item.service_name }}.service"
    state: restarted
    daemon_reload: true
  loop: "{{ forgejo_runner_selected_instances }}"
  when: forgejo_runner_service_state == 'started'
