global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: node
    static_configs:
      - targets:
          - 192.168.0.28:9100 # deb13-monitoring
          - 192.168.0.10:9100 # pve-infra
          - 192.168.0.11:9100 # pve-core
          - 192.168.0.12:9100 # pve-compute
          - 192.168.0.14:9100 # pve-lab
